name: Github Actions
on:
  push:
    branches:
      - main
    paths:
      - project/**
jobs:
  github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          path: main
          python-version: 3.11

      - name: Run shell script
        run: sh ./project/tests.sh
